presentation_generale_prompt = (
    "Vous devez structurer et organiser les informations relatives à la collectivité de {collectivite} "
    "Voici le format attendu :\n"
    " 1. Info Générales\n"
    "    - Collectivité : [nom]\n"
    "    - Habitants : [nombre] (année, gentilé)\n"
    "    - Superficie : [km²], densité : [hab./km²]\n"
    "2. Histoire et évolution administrative\n"
    "    - Réformes majeures : \n"
    "    - Dates clés : \n"
    "3. Caractéristiques clés: \n"
    "    - Secteurs économiques dominants :  \n"
    "    - Patrimoine et culture :  \n"
    "Utilisez les sources suivantes pour compléter et étayer votre fiche :\n"
    "------------------------------------------------------------\n"
    "{{context}}\n"
    "------------------------------------------------------------\n"
    "Veuillez intégrer ces informations de manière pertinente dans la rédaction de votre fiche."
)

tableau_projets_prompt = (
    "Vous devez transformer les informations relatives aux projets de la collectivité de {collectivite} "
    "en un tableau structuré selon le format suivant :\n"
    " 1. Thème\n"
    "    - Grande catégorie sous laquelle s’inscrit le projet (ex: Énergies renouvelables, Mobilité douce, Gestion de l’eau).\n"
    " 2. Catégorie de projets\n"
    "    - Type de projet spécifique (ex: Énergies solaires, Transport individuel, Service public de l’assainissement).\n"
    " 3. Principaux investissements en montants associés\n"
    "    - Investissements majeurs avec les montants associés lorsqu’ils sont disponibles.\n"
    " 4. Libellé politique publique ou budget\n"
    "    - Cadre budgétaire ou politique publique associée au projet (ex: Plan de Solarisation, Plan pluriannuel de rénovation des écoles).\n"
    "Format de sortie attendu : Markdown\n"
    "Utilisez les sources suivantes pour compléter et structurer le tableau :\n"
    "------------------------------------------------------------\n"
    "{{context}}\n"
    "------------------------------------------------------------\n"
    "Veuillez organiser les informations de manière claire et cohérente en respectant le format demandé."
)
